"""Render ROADMAP.md from docs/coverage.json.

Run after editing docs/coverage.json (e.g. after marking a newly-implemented
endpoint's status), or after re-running scripts/vendor_coverage.py.
"""
from __future__ import annotations

import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    data = json.loads((ROOT / "docs" / "coverage.json").read_text(encoding="utf-8"))
    endpoints = data["endpoints"]

    by_chapter: "OrderedDict[str, list[dict]]" = OrderedDict()
    for e in sorted(endpoints, key=lambda e: e["chapter_file"]):
        by_chapter.setdefault(e["chapter_file"], []).append(e)

    total = len(endpoints)
    implemented = sum(1 for e in endpoints if e["status"] == "implemented")

    lines = [
        "# Roadmap",
        "",
        f"Generated by `scripts/gen_roadmap.py` from `docs/coverage.json` "
        f"(vendored from {data['vendored_from']}).",
        "",
        f"**{implemented}/{total} documented endpoints implemented.**",
        "",
        "> " + data["source_note"],
        "",
        "Pick any unchecked row, implement it in the listed `module`, add a test "
        "mirroring the pattern in `tests/db/test_node_element.py` (or "
        "`tests/test_doc.py` for `/doc/`, `/ope/`, `/view/`-style plain-function "
        "endpoints), then mark it `\"implemented\"` in `docs/coverage.json` and "
        "re-run this script.",
        "",
    ]

    for chapter_file, rows in by_chapter.items():
        done = sum(1 for r in rows if r["status"] == "implemented")
        lines.append(f"## {chapter_file} ({done}/{len(rows)})")
        lines.append("")
        lines.append("| | Endpoint | Name | Products | Module |")
        lines.append("|---|---|---|---|---|")
        for r in rows:
            checkbox = "[x]" if r["status"] == "implemented" else "[ ]"
            products = "/".join(r["products"])
            lines.append(f"| {checkbox} | `{r['endpoint']}` | {r['name']} | {products} | `{r['module']}` |")
        lines.append("")

    (ROOT / "ROADMAP.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote ROADMAP.md - {implemented}/{total} implemented.")


if __name__ == "__main__":
    main()
