"""Render ROADMAP.md from docs/coverage.json.

Run after editing docs/coverage.json (e.g. after marking a newly-implemented
endpoint's status), or after re-running scripts/vendor_coverage.py.
"""
from __future__ import annotations

import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    data = json.loads((ROOT / "docs" / "coverage.json").read_text(encoding="utf-8"))
    endpoints = data["endpoints"]

    by_chapter: "OrderedDict[str, list[dict]]" = OrderedDict()
    for e in sorted(endpoints, key=lambda e: e["chapter_file"]):
        by_chapter.setdefault(e["chapter_file"], []).append(e)

    total = len(endpoints)
    implemented = sum(1 for e in endpoints if e["status"] == "implemented")
    live_verified = sum(1 for e in endpoints if e.get("live_verified"))

    # D4 version matrix: every distinct (date, Gen build, Civil build) combo
    # a live_verified entry cites — naturally grows into a real matrix as
    # more scripts/live_smoke.py runs get recorded over time.
    sessions = sorted({
        (
            e["live_verified"]["date"],
            e["live_verified"].get("nx_versions", {}).get("gen", "?"),
            e["live_verified"].get("nx_versions", {}).get("civil", "?"),
        )
        for e in endpoints
        if e.get("live_verified") and e["live_verified"].get("nx_versions")
    })

    lines = [
        "# Roadmap",
        "",
        f"Generated by `scripts/gen_roadmap.py` from `docs/coverage.json` "
        f"(vendored from {data['vendored_from']}).",
        "",
        f"**{implemented}/{total} documented endpoints implemented.**",
        "",
        f"**{live_verified}/{implemented} implemented endpoints live-verified** "
        "against a real Gen NX / Civil NX session (`live_verified` field in "
        "`docs/coverage.json`; see `scripts/live_smoke.py` and "
        "`docs/live_verification_notes.md`).",
        "",
    ]

    if sessions:
        lines.append("| Date | Gen NX build | Civil NX build |")
        lines.append("|---|---|---|")
        for date, gen_build, civil_build in sessions:
            lines.append(f"| {date} | {gen_build} | {civil_build} |")
        lines.append("")

    lines += [
        "> " + data["source_note"],
        "",
        "Pick any unchecked row, implement it in the listed `module`, add a test "
        "mirroring the pattern in `tests/db/test_node_element.py` (or "
        "`tests/test_doc.py` for `/doc/`, `/ope/`, `/view/`-style plain-function "
        "endpoints), then mark it `\"implemented\"` in `docs/coverage.json` and "
        "re-run this script.",
        "",
    ]

    for chapter_file, rows in by_chapter.items():
        done = sum(1 for r in rows if r["status"] == "implemented")
        lines.append(f"## {chapter_file} ({done}/{len(rows)})")
        lines.append("")
        lines.append("| | Live | Endpoint | Name | Products | Module |")
        lines.append("|---|---|---|---|---|---|")
        for r in rows:
            checkbox = "[x]" if r["status"] == "implemented" else "[ ]"
            live = "✅" if r.get("live_verified") else ""
            products = "/".join(r["products"])
            lines.append(f"| {checkbox} | {live} | `{r['endpoint']}` | {r['name']} | {products} | `{r['module']}` |")
        lines.append("")

    (ROOT / "ROADMAP.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote ROADMAP.md - {implemented}/{total} implemented.")


if __name__ == "__main__":
    main()
